
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "startFALSE NULL TRUE iCHAR iESCAPE iESCAPE_CHAR iFLOAT iINTEGER iKEYWORD iLBRACE iRBRACE\n    start : command\n          | label\n    \n    start : start command\n          | start label\n    \n    label : iKEYWORD ':'\n    \n    command : iKEYWORD\n    \n    command : iKEYWORD args\n    \n    command : iKEYWORD kwargs\n    \n    command : iKEYWORD args ',' kwargs\n    \n    args : value\n    \n    args : args ',' value\n    \n    value : iINTEGER\n    \n    value : iFLOAT\n    \n    value : TRUE\n          | FALSE\n    \n    value : NULL\n    \n    value : str\n    \n    value : keyword\n    \n    keyword : iKEYWORD\n    \n    keyword : keyword '.' iKEYWORD\n    \n    kwarg : iKEYWORD '=' value\n    \n    kwargs : kwarg\n    \n    kwargs : kwargs ',' kwarg\n    \n    str : iLBRACE chars iRBRACE\n    \n    chars : char\n    \n    chars : chars char\n    \n    char : iCHAR\n    \n    char : iESCAPE iESCAPE_CHAR\n    "
    
_lr_action_items = {'iKEYWORD':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,29,30,31,32,33,35,36,],[4,4,-1,-2,7,-3,-4,-19,-7,-8,-5,-10,-22,-12,-13,-14,-15,-16,-17,-18,29,7,34,35,-19,-21,-9,-11,-23,-20,-24,]),'$end':([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,29,30,31,32,33,35,36,],[0,-1,-2,-6,-3,-4,-19,-7,-8,-5,-10,-22,-12,-13,-14,-15,-16,-17,-18,-19,-21,-9,-11,-23,-20,-24,]),':':([4,],[10,]),'iINTEGER':([4,21,22,],[13,13,13,]),'iFLOAT':([4,21,22,],[14,14,14,]),'TRUE':([4,21,22,],[15,15,15,]),'FALSE':([4,21,22,],[16,16,16,]),'NULL':([4,21,22,],[17,17,17,]),'iLBRACE':([4,21,22,],[20,20,20,]),'=':([7,34,],[21,21,]),'.':([7,19,29,35,],[-19,24,-19,-20,]),',':([7,8,9,11,12,13,14,15,16,17,18,19,29,30,31,32,33,35,36,],[-19,22,23,-10,-22,-12,-13,-14,-15,-16,-17,-18,-19,-21,23,-11,-23,-20,-24,]),'iCHAR':([20,25,26,27,37,38,],[27,27,-25,-27,-26,-28,]),'iESCAPE':([20,25,26,27,37,38,],[28,28,-25,-27,-26,-28,]),'iRBRACE':([25,26,27,37,38,],[36,-25,-27,-26,-28,]),'iESCAPE_CHAR':([28,],[38,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'command':([0,1,],[2,5,]),'label':([0,1,],[3,6,]),'args':([4,],[8,]),'kwargs':([4,22,],[9,31,]),'value':([4,21,22,],[11,30,32,]),'kwarg':([4,22,23,],[12,12,33,]),'str':([4,21,22,],[18,18,18,]),'keyword':([4,21,22,],[19,19,19,]),'chars':([20,],[25,]),'char':([20,25,],[26,37,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> command','start',1,'p_start','yacc.py',12),
  ('start -> label','start',1,'p_start','yacc.py',13),
  ('start -> start command','start',2,'p_start_1','yacc.py',20),
  ('start -> start label','start',2,'p_start_1','yacc.py',21),
  ('label -> iKEYWORD :','label',2,'p_label','yacc.py',28),
  ('command -> iKEYWORD','command',1,'p_command','yacc.py',35),
  ('command -> iKEYWORD args','command',2,'p_command_1','yacc.py',42),
  ('command -> iKEYWORD kwargs','command',2,'p_command_2','yacc.py',49),
  ('command -> iKEYWORD args , kwargs','command',4,'p_command_3','yacc.py',56),
  ('args -> value','args',1,'p_args','yacc.py',63),
  ('args -> args , value','args',3,'p_args_1','yacc.py',70),
  ('value -> iINTEGER','value',1,'p_value_int','yacc.py',77),
  ('value -> iFLOAT','value',1,'p_value_float','yacc.py',84),
  ('value -> TRUE','value',1,'p_value_bool','yacc.py',91),
  ('value -> FALSE','value',1,'p_value_bool','yacc.py',92),
  ('value -> NULL','value',1,'p_value_null','yacc.py',99),
  ('value -> str','value',1,'p_value_str','yacc.py',106),
  ('value -> keyword','value',1,'p_value_keyword','yacc.py',113),
  ('keyword -> iKEYWORD','keyword',1,'p_keyword','yacc.py',120),
  ('keyword -> keyword . iKEYWORD','keyword',3,'p_keyword_1','yacc.py',127),
  ('kwarg -> iKEYWORD = value','kwarg',3,'p_kwarg','yacc.py',134),
  ('kwargs -> kwarg','kwargs',1,'p_kwargs','yacc.py',141),
  ('kwargs -> kwargs , kwarg','kwargs',3,'p_kwargs_1','yacc.py',148),
  ('str -> iLBRACE chars iRBRACE','str',3,'p_str','yacc.py',155),
  ('chars -> char','chars',1,'p_chars','yacc.py',162),
  ('chars -> chars char','chars',2,'p_chars_1','yacc.py',169),
  ('char -> iCHAR','char',1,'p_char','yacc.py',176),
  ('char -> iESCAPE iESCAPE_CHAR','char',2,'p_char_escape','yacc.py',183),
]
